
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 106
#define YY_END_OF_BUFFER 107
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[356] =
    {   0,
        0,    0,  107,  105,  103,  104,   87,  105,   93,   86,
      105,   81,   82,   91,   90,   78,   89,   85,   92,   43,
       43,   79,   75,   94,   80,   95,   98,   40,   40,   83,
      105,   84,   96,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   76,
       97,   77,   88,  102,   74,    0,   52,    0,   60,   77,
       69,   61,    0,    0,   58,   66,   56,   67,   57,   68,
        0,   47,   59,   48,   42,    0,   43,    0,   43,   84,
       76,   83,   65,   71,   73,   72,   64,   40,    0,    0,
        0,    0,    0,   62,   40,   40,   40,   40,   40,   40,

       40,   40,   40,   40,   40,   12,   40,   40,   40,   40,
       40,   40,   20,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   63,   70,  102,  102,  102,  102,
       45,   53,    0,   47,   47,   47,    0,   48,   48,   42,
        0,   46,    0,   41,   55,   54,    0,    0,    0,    0,
        0,    0,   40,   40,   40,   40,    2,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   18,   40,
       40,   23,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,  102,  102,
      102,    0,   47,    0,   47,   47,    0,   48,   46,   46,

        0,    0,   41,    0,    0,    0,   44,    0,    0,   40,
       40,   40,   40,    3,   40,    6,    7,   40,   40,   40,
       40,   14,   15,   40,   40,   19,   40,   24,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       37,   40,   40,  102,  102,  102,    0,   47,    0,    0,
        0,   51,    0,    0,    0,    0,    4,   40,   40,   40,
        5,    9,   40,   40,   40,   40,   17,   40,   40,   40,
       40,   28,   40,   40,   40,   40,   40,   40,   35,   40,
       40,   39,  102,  102,  102,    0,   49,    0,   50,   51,
       51,    0,    0,    0,   40,   40,   40,   40,   40,   40,

       13,   16,   22,   40,   40,   27,   29,   30,   31,   32,
       33,   40,   40,   40,  102,  101,  102,   49,   49,   50,
       50,    0,    0,   40,   40,   40,   40,   11,   40,   40,
       34,   40,   40,  100,  101,  102,    0,    0,    8,   40,
        1,   10,   25,   26,   36,   38,  100,   99,    0,    0,
       40,   99,    0,   21,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   27,   30,   31,
       32,   32,   33,   32,   32,   34,   32,   32,   32,   35,
       32,   32,   32,   32,   36,   32,   32,   37,   32,   32,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   32,   52,   53,   54,   55,
       56,   57,   32,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    4,    1,    5,    5,
        1,    1,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    6,    6,    6,    6,    6,    6,    1,    6,    1,
        1,    6,    5,    5,    5,    5,    5,    5,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[388] =
    {   0,
        0,  735,  741,  743,  743,  743,  716,   65,   48,   65,
      700,  743,  743,  714,   61,  743,   62,   60,  713,   88,
       76,  711,  743,   76,  711,   57,  743,  695,   82,  743,
       40,  743,  709,  103,   52,   44,   77,   70,   75,   95,
       59,   99,  101,  111,  105,  104,   64,  107,  114,  743,
      135,  743,  743,  109,  743,  155,  743,  729,  743,  743,
      743,  743,  157,  167,  743,  743,  743,  743,  743,  743,
      714,  153,  743,  161,  196,  191,  183,  713,  201,  743,
      743,  743,  705,  743,  743,  743,  704,  688,  138,  183,
      687,    0,    0,  743,  132,  137,  136,  185,  143,  163,

      139,  186,   51,  195,  190,  200,  188,  202,  207,  203,
      140,  212,  686,  213,  201,  216,  214,  219,  221,  230,
      232,  235,  239,  244,  743,  743,    0,  678,  672,  664,
      743,  743,  268,  670,  743,  277,  284,  669,  743,  257,
      282,  286,    0,  297,  743,  743,    0,    0,  270,  309,
        0,    0,  260,  282,  283,  274,  680,  284,  299,  302,
      288,  304,  305,  308,  306,  312,  318,  316,  679,  317,
      321,  678,  322,  323,  328,  329,  331,  330,  336,  337,
      338,  340,  339,  342,  341,  345,  362,  276,  669,  660,
      671,  374,  376,  392,  662,  743,  383,  394,  661,  743,

      347,  352,  382,  401,    0,    0,  743,    0,    0,  380,
      383,  387,  384,  672,  392,  671,  670,  391,  395,  393,
      399,  669,  668,  398,  402,  667,  409,  666,  410,  414,
      416,  411,  418,  419,  422,  421,  431,  438,  424,  429,
      665,  420,  442,  648,  655,  652,  463,  466,  474,  482,
      472,  484,    0,    0,    0,    0,  661,  456,  448,  466,
      660,  659,  467,  468,  469,  471,  658,  473,  474,  485,
      484,  657,  492,  494,  501,  488,  491,  504,  656,  489,
      506,  655,  633,  690,  637,  530,  533,  535,  539,  639,
      743,    0,    0,    0,  650,  521,  508,  523,  517,  522,

      649,  648,  647,  527,  530,  646,  645,  644,  643,  642,
      641,  532,  538,  540,  677,    0,  635,  626,  743,  625,
      743,    0,    0,  533,  486,  549,  555,  636,  537,  544,
      635,  550,  559,    0,    0,  671,    0,    0,  629,  560,
      623,  617,  612,  603,  596,  586,    0,    0,    0,    0,
      561,    0,    0,  585,  743,  626,  632,  634,  640,  643,
      648,  618,  617,  616,  615,  614,  612,  611,  610,  609,
      608,  607,  606,  605,  604,  603,  602,  600,  598,  654,
      596,  462,  660,  272,  223,  666,  180
    } ;

static const flex_int16_t yy_def[388] =
    {   0,
      355,    1,  355,  355,  355,  355,  355,  356,  355,  355,
      357,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  358,  358,  355,
      355,  355,  355,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  355,
      355,  355,  355,  359,  355,  356,  355,  356,  355,  355,
      355,  355,  357,  357,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  360,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  358,  355,  356,
      361,  362,  363,  355,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  355,  355,  359,  359,  359,  359,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  364,  360,  355,  355,  365,  366,  361,  361,
      367,  368,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  359,  359,
      359,  355,  355,  355,  355,  355,  355,  355,  355,  355,

      364,  364,  355,  355,  369,  370,  355,  371,  372,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  359,  359,  359,  355,  355,  355,  355,
      355,  355,  373,  374,  375,  376,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  359,  359,  359,  355,  355,  355,  355,  355,
      355,  377,  378,  379,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  359,  380,  359,  355,  355,  355,
      355,  381,  382,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  383,  380,  359,  384,  385,  358,  358,
      358,  358,  358,  358,  358,  358,  383,  386,  387,  376,
      358,  386,  378,  358,    0,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355
    } ;

static const flex_int16_t yy_nxt[814] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   28,   28,   28,
       28,   28,   28,   29,   28,   28,   28,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   28,
       42,   28,   43,   28,   28,   28,   28,   44,   45,   46,
       47,   48,   49,   28,   28,   28,   50,   51,   52,   53,
       57,   59,   60,   61,   66,   92,   71,   68,   72,   72,
       86,   87,   89,   81,   67,   69,   70,   90,   62,   89,
       89,   91,   74,  161,   79,   79,   82,   89,   83,   84,

       93,  101,   89,   58,   74,   76,   75,   75,   89,   77,
       99,   77,  100,   89,  112,   89,  105,   76,  122,  102,
       89,   77,   76,   77,   78,  106,  103,  107,   77,  108,
       95,   96,  104,   89,   76,   97,   77,   89,  109,   89,
       77,   89,   89,   89,   98,   89,  113,  110,   77,   89,
      111,   78,   89,  114,  117,  118,  115,  116,  125,  128,
       57,  129,  123,  124,  119,  130,  131,  120,  121,  355,
       89,   72,   72,  147,   89,   89,   63,   89,   89,  136,
      136,   89,  133,  134,  353,  159,  134,  153,   57,  155,
      137,  138,  154,   58,  138,   64,  157,  169,  148,  133,

      134,   89,  126,  135,  141,  134,  141,  137,  138,  142,
      142,  139,   74,  138,   75,   75,   77,   74,   77,   79,
       79,   58,  158,   89,   89,   76,   89,  350,   89,  140,
       76,  140,  156,   89,   77,   77,   77,  163,   89,   89,
       89,   89,   76,   77,  160,   89,  165,   76,  140,  162,
       89,   89,   89,   77,   89,  173,  140,   89,  168,   89,
      164,   77,  166,  180,  174,  171,  167,  178,   89,  177,
       89,  170,  172,   89,  175,  176,  349,   89,  181,  207,
      182,  192,   89,  192,  179,  184,  193,  193,  183,  186,
      140,  187,  140,  185,  188,  136,  136,  197,   89,  197,

      142,  142,  198,  198,  142,  142,  194,  195,  150,  140,
      195,  355,   89,  202,   89,  210,  199,  140,  149,  199,
       89,   89,   89,  194,  195,  212,   89,  196,  243,  195,
      203,  204,  203,  199,  213,  211,  200,   89,  199,  214,
       89,  215,   89,   89,   89,  217,   89,  220,  216,  203,
       89,  221,  222,  204,   89,   89,   89,  203,  225,   89,
       89,   89,  218,  219,  224,  223,   89,   89,   89,   89,
      228,  227,  226,  229,   89,   89,   89,   89,   89,   89,
       89,  249,  234,   89,  233,  238,  250,  230,  232,  231,
      241,  240,  193,  193,  193,  193,  235,  239,  236,  237,

       89,  198,  198,  249,  242,  247,  134,  247,  250,  134,
      248,  248,  198,  198,  251,  203,  251,  203,   89,  252,
      252,   89,   89,  134,  138,   89,  135,  138,  134,   89,
       89,   89,  257,   89,  203,  259,   89,   89,  260,  258,
       89,  138,  203,  261,  139,  263,  138,   89,   89,   89,
      262,  265,   89,  264,   89,  266,   89,   89,   89,   89,
       89,  267,   89,  268,  273,  276,  338,   89,  269,   89,
      272,  270,  275,  271,  274,  277,   89,  280,  279,  281,
       89,  248,  248,  278,  248,  248,   89,  286,  282,  286,
      252,  252,  287,  287,   89,  288,  195,  288,  297,  195,

      289,  289,  252,  252,   89,   89,   89,   89,  296,   89,
      298,   89,   89,  195,  290,  301,  196,  290,  195,  303,
      300,  299,   89,   89,   89,  302,   89,   89,  340,   89,
       89,  290,   89,  304,  291,  305,  290,  307,  306,   89,
      311,  308,   89,  313,   89,  309,   89,  310,  287,  287,
      312,  287,  287,  289,  289,   89,  314,  289,  289,   89,
       89,   89,  325,  318,  326,   89,  318,  324,   89,  320,
       89,   89,  320,  329,  330,   89,   89,  327,   89,  331,
      318,  328,   89,  319,  332,  318,  320,   89,   89,  321,
      341,  320,  333,   89,  343,  345,  339,   89,   89,   89,

      337,  342,  323,  344,   88,  346,  322,  295,  294,  293,
      292,  256,  255,  254,  253,  209,  208,  351,  206,  205,
      201,  152,  151,   89,   89,  354,   56,   56,   56,   56,
       56,   56,   63,   63,   89,   63,   63,   63,   88,   88,
      127,   89,  127,  127,  127,  127,  144,  144,  149,  149,
       89,  149,  149,  149,  335,   89,  335,  335,  335,  335,
      347,   89,  347,  347,  347,  347,  352,   89,  352,  352,
      352,  352,  348,   89,   89,  321,  319,  336,  334,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,  291,
      317,  316,  315,   89,   89,   89,   89,   89,   89,   89,

      285,  284,  283,   89,   89,   89,   89,   89,   89,   89,
       89,  200,  196,  246,  245,  244,   89,   89,   89,  139,
      135,  191,  190,  189,   89,  150,   89,  146,  145,  143,
      132,  355,   94,   89,   85,   80,   73,   65,   64,   55,
      355,   54,    3,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355
    } ;

static const flex_int16_t yy_chk[814] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        8,    9,    9,   10,   15,   31,   18,   17,   18,   18,
       26,   26,   36,   24,   15,   17,   17,   29,   10,  103,
       35,   29,   21,  103,   21,   21,   24,   41,   24,   24,

       31,   36,   47,    8,   20,   21,   20,   20,   38,   21,
       35,   21,   35,   39,   41,   37,   38,   20,   47,   37,
       29,   20,   21,   20,   20,   38,   37,   39,   21,   39,
       34,   34,   37,   40,   20,   34,   21,   42,   39,   43,
       20,   34,   46,   45,   34,   48,   42,   40,   20,   44,
       40,   20,   49,   42,   45,   45,   43,   44,   51,   54,
       56,   54,   48,   49,   45,   54,   63,   45,   46,   64,
       95,   72,   72,   89,   97,   96,   64,  101,  111,   74,
       74,   99,   72,   72,  387,  101,   72,   95,   90,   97,
       74,   74,   96,   56,   74,   63,   99,  111,   89,   72,

       72,  100,   51,   72,   76,   72,   76,   74,   74,   76,
       76,   74,   75,   74,   75,   75,   77,   79,   77,   79,
       79,   90,  100,   98,  102,   75,  107,  385,  105,   75,
       79,   75,   98,  104,   79,   77,   79,  105,  106,  115,
      108,  110,   75,   77,  102,  109,  107,   79,   75,  104,
      112,  114,  117,   79,  116,  115,   75,  118,  110,  119,
      106,   79,  108,  119,  116,  114,  109,  118,  120,  117,
      121,  112,  114,  122,  116,  116,  384,  123,  119,  149,
      120,  133,  124,  133,  118,  122,  133,  133,  121,  123,
      140,  123,  140,  122,  124,  136,  136,  137,  153,  137,

      141,  141,  137,  137,  142,  142,  136,  136,  149,  140,
      136,  150,  156,  144,  188,  153,  142,  140,  150,  142,
      154,  155,  158,  136,  136,  155,  161,  136,  188,  136,
      144,  144,  144,  142,  156,  154,  142,  159,  142,  158,
      160,  159,  162,  163,  165,  161,  164,  163,  160,  144,
      166,  164,  165,  144,  168,  170,  167,  144,  168,  171,
      173,  174,  162,  162,  167,  166,  175,  176,  178,  177,
      173,  171,  170,  174,  179,  180,  181,  183,  182,  185,
      184,  201,  179,  186,  178,  183,  202,  175,  177,  176,
      186,  185,  192,  192,  193,  193,  180,  184,  181,  182,

      187,  197,  197,  201,  187,  194,  193,  194,  202,  193,
      194,  194,  198,  198,  204,  203,  204,  203,  210,  204,
      204,  211,  213,  193,  198,  212,  193,  198,  193,  218,
      215,  220,  210,  219,  203,  212,  224,  221,  213,  211,
      225,  198,  203,  215,  198,  219,  198,  227,  229,  232,
      218,  221,  230,  220,  231,  224,  233,  234,  242,  236,
      235,  225,  239,  227,  233,  236,  382,  240,  229,  237,
      232,  230,  235,  231,  234,  237,  238,  240,  239,  242,
      243,  247,  247,  238,  248,  248,  259,  249,  243,  249,
      251,  251,  249,  249,  258,  250,  248,  250,  259,  248,

      250,  250,  252,  252,  260,  263,  264,  265,  258,  266,
      260,  268,  269,  248,  252,  265,  248,  252,  248,  268,
      264,  263,  271,  270,  325,  266,  276,  280,  325,  277,
      273,  252,  274,  269,  252,  270,  252,  273,  271,  275,
      277,  274,  278,  280,  281,  275,  297,  276,  286,  286,
      278,  287,  287,  288,  288,  299,  281,  289,  289,  296,
      300,  298,  297,  287,  298,  304,  287,  296,  305,  289,
      312,  324,  289,  304,  305,  329,  313,  299,  314,  312,
      287,  300,  330,  287,  313,  287,  289,  326,  332,  289,
      326,  289,  314,  327,  329,  332,  324,  333,  340,  351,

      381,  327,  379,  330,  378,  333,  377,  376,  375,  374,
      373,  372,  371,  370,  369,  368,  367,  340,  366,  365,
      364,  363,  362,  354,  346,  351,  356,  356,  356,  356,
      356,  356,  357,  357,  345,  357,  357,  357,  358,  358,
      359,  344,  359,  359,  359,  359,  360,  360,  361,  361,
      343,  361,  361,  361,  380,  342,  380,  380,  380,  380,
      383,  341,  383,  383,  383,  383,  386,  339,  386,  386,
      386,  386,  336,  331,  328,  320,  318,  317,  315,  311,
      310,  309,  308,  307,  306,  303,  302,  301,  295,  290,
      285,  284,  283,  282,  279,  272,  267,  262,  261,  257,

      246,  245,  244,  241,  228,  226,  223,  222,  217,  216,
      214,  199,  195,  191,  190,  189,  172,  169,  157,  138,
      134,  130,  129,  128,  113,   91,   88,   87,   83,   78,
       71,   58,   33,   28,   25,   22,   19,   14,   11,    7,
        3,    2,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scan.l"
#line 2 "scan.l"
/*
 * Copyright (c) 2002 Anders Magnusson. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifdef CROSS
#   include </usr/include/stdio.h>
#   include </usr/include/errno.h>
#else
#   include <stdio.h>
#   include <errno.h>
#endif
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

#include "pass1.h"
#include "cgram.h"
#line 783 "lex.yy.c"
#line 53 "scan.l"
static NODE *cvtdig(int radix);
static NODE *charcon(void);
static NODE *wcharcon(void);
static void control(int);
static void pragma(void);
int notype, parbal, inattr, parlvl;
static int resw(TWORD, int);

#define	CPP_IDENT 	2
#define	CPP_LINE 	3
#define	CPP_HASH	4

#ifdef STABS
#   define STABS_LINE(x) if (gflag && cftnsp) stabs_line(x)
#else
#   define STABS_LINE(x)
#endif
#if defined(FLEX_SCANNER) && YY_FLEX_SUBMINOR_VERSION == 31
/* Hack to avoid unnecessary warnings */
FILE *yyget_in  (void);
FILE *yyget_out  (void);
int yyget_leng  (void);
char *yyget_text  (void);
void yyset_in (FILE *);
void yyset_out (FILE *);
int yyget_debug  (void);
void yyset_debug (int);
int yylex_destroy  (void);
extern int yyget_lineno (void);
extern void yyset_lineno (int);
#endif
#line 816 "lex.yy.c"
#line 817 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 86 "scan.l"


#line 1040 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 356 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 743 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 88 "scan.l"
{
				if (cftnsp == NULL)
					uerror("__func__ outside function");
				yylval.strp = cftnsp->sname; /* XXX - not C99 */
				return(C_STRING);
			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 94 "scan.l"
{ return(C_ASM); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 95 "scan.l"
{ 	return resw(AUTO, C_CLASS); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 96 "scan.l"
{ 	return resw(BOOL, C_TYPE); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 97 "scan.l"
{ return(C_BREAK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 98 "scan.l"
{ return(C_CASE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 99 "scan.l"
{ 	return resw(CHAR, C_TYPE); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 100 "scan.l"
{ 	return resw(COMPLEX, C_TYPE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 101 "scan.l"
{ 	return resw(CON, C_QUALIFIER); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 102 "scan.l"
{ return(C_CONTINUE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 103 "scan.l"
{ return(C_DEFAULT); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 104 "scan.l"
{ return(C_DO); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 105 "scan.l"
{ 	return resw(DOUBLE, C_TYPE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 106 "scan.l"
{ return(C_ELSE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 107 "scan.l"
{ notype=1; return(C_ENUM); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 108 "scan.l"
{ 	return resw(EXTERN, C_CLASS); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 109 "scan.l"
{ 	return resw(FLOAT, C_TYPE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 110 "scan.l"
{ return(C_FOR); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 111 "scan.l"
{ notype=1; return(C_GOTO); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 112 "scan.l"
{ return(C_IF); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 113 "scan.l"
{ 	return resw(IMAG, C_TYPE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 114 "scan.l"
{ return(C_FUNSPEC); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 115 "scan.l"
{ 	return resw(INT, C_TYPE); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 116 "scan.l"
{ 	return resw(LONG, C_TYPE); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 117 "scan.l"
{ 	return resw(REGISTER, C_CLASS); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 118 "scan.l"
{ ; /* just ignore */ }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 119 "scan.l"
{ return(C_RETURN); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 120 "scan.l"
{ 	return resw(SHORT, C_TYPE); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 121 "scan.l"
{ 	return resw(SIGNED, C_TYPE); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 122 "scan.l"
{ return(C_SIZEOF); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 123 "scan.l"
{ 	return resw(STATIC, C_CLASS); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 124 "scan.l"
{ yylval.intval = STNAME; notype=1; return(C_STRUCT); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 125 "scan.l"
{ return(C_SWITCH); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 126 "scan.l"
{ 	return resw(TYPEDEF, C_CLASS); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 127 "scan.l"
{ yylval.intval = UNAME; notype=1; return(C_STRUCT); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 128 "scan.l"
{ 	return resw(UNSIGNED, C_TYPE); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 129 "scan.l"
{ 	return resw(VOID, C_TYPE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 130 "scan.l"
{	return resw(VOL, C_QUALIFIER); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 131 "scan.l"
{ return(C_WHILE); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 133 "scan.l"
{ 	struct symtab *s;
			int i = 0;

			yylval.strp = addname(yytext);
#ifdef GCC_COMPAT
			if ((i = gcc_keyword(yylval.strp, &yylval.nodep)) > 0)
				return i;
#endif
			if (i == 0) {
				if (notype)
					return(C_NAME);
				s = lookup(yylval.strp, SNOCREAT);
				return s && s->sclass == TYPEDEF ?
				    notype=1, C_TYPENAME : C_NAME;
			}
		}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 150 "scan.l"
{ yylval.nodep = cvtdig(16); return(C_ICON); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 151 "scan.l"
{ yylval.nodep = cvtdig(8); return(C_ICON); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 152 "scan.l"
{ yylval.nodep = cvtdig(10); return(C_ICON); }
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 153 "scan.l"
{ yylval.nodep = wcharcon(); return(C_ICON); }
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 154 "scan.l"
{ yylval.nodep = charcon(); return(C_ICON); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 156 "scan.l"
{ yylval.nodep = floatcon(yytext); return(C_FCON); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 157 "scan.l"
{ yylval.nodep = floatcon(yytext); return(C_FCON); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 158 "scan.l"
{ yylval.nodep = floatcon(yytext); return(C_FCON); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 159 "scan.l"
{ yylval.nodep = fhexcon(yytext); return(C_FCON); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 160 "scan.l"
{ yylval.nodep = fhexcon(yytext); return(C_FCON); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 161 "scan.l"
{ yylval.nodep = fhexcon(yytext); return(C_FCON); }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 163 "scan.l"
{ yylval.strp = yytext; return C_STRING; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 165 "scan.l"
{ return(C_ELLIPSIS); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 166 "scan.l"
{ yylval.intval = RSEQ; return(C_ASOP); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 167 "scan.l"
{ yylval.intval = LSEQ; return(C_ASOP); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 168 "scan.l"
{ yylval.intval = PLUSEQ; return(C_ASOP); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 169 "scan.l"
{ yylval.intval = MINUSEQ; return(C_ASOP); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 170 "scan.l"
{ yylval.intval = MULEQ; return(C_ASOP); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 171 "scan.l"
{ yylval.intval = DIVEQ; return(C_ASOP); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 172 "scan.l"
{ yylval.intval = MODEQ; return(C_ASOP); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 173 "scan.l"
{ yylval.intval = ANDEQ; return(C_ASOP); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 174 "scan.l"
{ yylval.intval = EREQ; return(C_ASOP); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 175 "scan.l"
{ yylval.intval = OREQ; return(C_ASOP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 176 "scan.l"
{ yylval.intval = RS; return(C_SHIFTOP); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 177 "scan.l"
{ yylval.intval = LS; return(C_SHIFTOP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 178 "scan.l"
{ yylval.intval = INCR; return(C_INCOP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 179 "scan.l"
{ yylval.intval = DECR; return(C_INCOP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 180 "scan.l"
{ yylval.intval = STREF; return(C_STROP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 181 "scan.l"
{ yylval.intval = ANDAND; return(C_ANDAND); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 182 "scan.l"
{ yylval.intval = OROR; return(C_OROR); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 183 "scan.l"
{ yylval.intval = LE; return(C_RELOP); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 184 "scan.l"
{ yylval.intval = GE; return(C_RELOP); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 185 "scan.l"
{ yylval.intval = EQ; return(C_EQUOP); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 186 "scan.l"
{ yylval.intval = NE; return(C_EQUOP); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 187 "scan.l"
{ notype = 0; return(';'); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 188 "scan.l"
{ notype = 0; return('{'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 189 "scan.l"
{ if (rpole) notype = 1; return('}'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 190 "scan.l"
{ if (parbal) notype = 0; return(','); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 191 "scan.l"
{ return(':'); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 192 "scan.l"
{ return('='); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 193 "scan.l"
{ parbal++; notype = 0; return('('); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 194 "scan.l"
{	parbal--;
				if (parbal==0) { notype = 0; }
				if (inattr && parlvl == parbal)
					inattr = 0;
				return(')'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 199 "scan.l"
{ return('['); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 200 "scan.l"
{ return(']'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 201 "scan.l"
{ yylval.intval = DOT; return(C_STROP); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 202 "scan.l"
{ return('&'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 203 "scan.l"
{ yylval.intval = NOT; return(C_UNOP); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 204 "scan.l"
{ yylval.intval = COMPL; return(C_UNOP); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 205 "scan.l"
{ return('-'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 206 "scan.l"
{ return('+'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 207 "scan.l"
{ if (parbal && notype == 0) notype = 1; return('*'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 208 "scan.l"
{ yylval.intval = DIV; return(C_DIVOP); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 209 "scan.l"
{ yylval.intval = MOD; return(C_DIVOP); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 210 "scan.l"
{ yylval.intval = LT; return(C_RELOP); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 211 "scan.l"
{ yylval.intval = GT; return(C_RELOP); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 212 "scan.l"
{ return('^'); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 213 "scan.l"
{ return('|'); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 214 "scan.l"
{ return('?'); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 215 "scan.l"
{ pragma(); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 216 "scan.l"
{ control(CPP_IDENT); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 217 "scan.l"
{ control(CPP_LINE); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 218 "scan.l"
{ control(CPP_HASH); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 220 "scan.l"
{ }
	YY_BREAK
case 104:
/* rule 104 can match eol */
YY_RULE_SETUP
#line 221 "scan.l"
{ ++lineno; STABS_LINE(lineno); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 222 "scan.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 224 "scan.l"
ECHO;
	YY_BREAK
#line 1656 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 356 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 356 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 355);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 224 "scan.l"


char *ftitle = "<stdin>";

int
yywrap(void)
{
	if (0) unput(0); /* quiet gcc */
	return(1);
}

int
resw(TWORD t, int rv)
{
	if (inattr) {
		yylval.strp = addname(yytext);
		return C_NAME;
	}

	switch (rv) {
	case C_CLASS:
		yylval.nodep = block(CLASS, NIL, NIL, t, 0, 0);
		return rv;

	case C_QUALIFIER:
		yylval.nodep = block(QUALIFIER, NIL, NIL, 0, 0, 0);
		yylval.nodep->n_qual = t;
		return rv;

	case C_TYPE:
		yylval.nodep = mkty(t, 0, MKAP(t));
		notype=1;
		return(rv);

	default:
		cerror("resw");
	}
	return 0;
}

#ifndef SOFTFLOAT
/*
 * XXX floatcon() and fhexcon() should be in support libraries for
 * the target floating point.
 */
static NODE *
f2(char *str)
{
	TWORD tw;
	NODE *p;
	long double dc;
	char *eptr;
	int imag = 0;

#ifdef HAVE_STRTOLD
	dc = strtold(str, &eptr); /* XXX - avoid strtod() */
#else
	dc = strtod(str, &eptr); /* XXX - avoid strtod() */
#endif
	tw = DOUBLE;
	for (; *eptr; eptr++) {
		switch (*eptr) {
		case 'f':
		case 'F':
			tw = FLOAT;
			dc = (float)dc;
			break;
		case 'l':
		case 'L':
			tw = LDOUBLE;
			break;
		case 'i':
		case 'I':
			imag = 1;
			break;
		}
	}
	if (tw == DOUBLE)
		dc = (double)dc;
#ifndef NO_COMPLEX
	if (imag)
		tw += (FIMAG-FLOAT);
#endif
	p = block(FCON, NIL, NIL, tw, 0, MKAP(tw));
	p->n_dcon = dc;
	return p;
}

NODE *
floatcon(char *s)
{
	return f2(s);
}

static int
h2n(int ch)
{
	if (ch >= '0' && ch <= '9')
		return ch - '0';
	if (ch >= 'a' && ch <= 'f')
		return ch - 'a' + 10;
	return ch - 'A' + 10;

}

NODE *
fhexcon(char *c)
{
	char buf[500];
	unsigned long long num1, num2;

	/* XXX - convert it to a decimal float number and use strtod */
	c+= 2; /* skip 0x */
	for (num1 = 0; *c != '.' && *c != 'p' && *c != 'P'; c++)
		num1 = (num1 << 4) | h2n(*c);
	if (*c != '.' && *c != 'p' && *c != 'P')
		cerror("fhexcon");
	num2 = 0;
	if (*c == '.') {
		c++;
		for (; *c != 'p' && *c != 'P'; c++)
			num2 = (num2 << 4) | h2n(*c);
	}
	if (*c != 'P' && *c != 'p')
		cerror("fhexcon2");
	c++;
	snprintf(buf, sizeof(buf), "%llu.%lluE%s", num1, num2, c);
	return f2(buf);
}
#endif

unsigned int
esccon(char **sptr)
{
	char *wr = *sptr;
	char *owr;
	char c;
	unsigned int val;
	int wsz = 4, esccon_warn = 1;

	switch (*wr++) {
	case 'a': val = '\a'; break;
	case 'b': val = '\b'; break;
	case 'f': val = '\f'; break;
	case 'n': val = '\n'; break;
	case 'r': val = '\r'; break;
	case 't': val = '\t'; break;
	case 'v': val = '\v'; break;
	case '\"': val = '\"'; break;
	case 'x': val = strtoul(wr, &wr, 16); break;
	/* ISO/IEC 9099:1999 (E) 6.4.3 */
	case 'U'|(char)0x80:
		esccon_warn = 0;
		/* FALLTHROUGH */
	case 'U':
		wsz = 8;
		/* FALLTHROUGH */
	case 'u':
		owr = wr;
		while (wr < (owr + wsz))
			if (*wr == '\0')
				break;
			else
				++wr;
		if (wr != (owr + wsz)) {
			/* incomplete */
			val = strtoul(owr, &wr, 16);
		} else {
			c = owr[wsz];
			owr[wsz] = '\0'; /* prevent it from reading too much */
			val = strtoul(owr, &wr, 16);
			owr[wsz] = c;
		}
		if (wr != (owr + wsz))
			werror("incomplete universal character name");
		if (wsz == 4)
			val &= 0xFFFF;
		if (esccon_warn && ((val >= 0xD800 && val <= 0xDFFF) ||
		    (val < 0xA0 && val != 0x24 && val != 0x40 && val != 0x60)))
			werror("invalid universal character name %04X", val);
		break;
	case '0': case '1': case '2': case '3': case '4':
	case '5': case '6': case '7':
		val = wr[-1] - '0';
		if (*wr >= '0' && *wr <= '7') {
			val = (val << 3) + (*wr++ - '0');
			if (*wr >= '0' && *wr <= '7')
				val = (val << 3) + (*wr++ - '0');
		}
		break;
	default: val = wr[-1];
	}
	*sptr = wr;
	return val;
}

NODE *
cvtdig(int radix)
{
	NODE *p;
	TWORD ntype;
	unsigned long long v;
	char *ch = yytext;
	int n, numl, numu;

	if (radix == 16)
		ch += 2; /* Skip 0x */

	v = 0;
	while ((*ch >= '0' && *ch <= '9') || (*ch >= 'a' && *ch <= 'f') ||
	    (*ch >= 'A' && *ch <= 'F')) {
		v *= radix;
		n = *ch;
		n = (n <= '9' ? n - '0' : (n > 'F' ? n - 'a' : n - 'A') + 10);
		ch++;
		v += n;
	}
	/* Parse trailing chars */
	ntype = INT;
	numl = numu = 0;
	for (n = 0; n < 3; n++) {
		if (*ch == 0)
			break;
		if ((*ch == 'l' || *ch == 'L') && numl < 2)
			ntype+=2, numl++;
		else if ((*ch == 'u' || *ch == 'U') && numu < 1)
			ntype = ENUNSIGN(ntype), numu++;
		else
			break;
		ch++;
	}
	if (*ch)
		uerror("constant has too many '%c'", *ch);

	if (ntype == INT) {
		/* v contains a number. Get type correct */
		if (v > MAX_LONGLONG && radix != 10)
			ntype = ULONGLONG;
		else if (v > MAX_ULONG)
			ntype = LONGLONG;
		else if (v > MAX_LONG && radix != 10)
			ntype = ULONG;
		else if (v > MAX_UNSIGNED)
			ntype = LONG;
		else if (v > MAX_INT && radix != 10)
			ntype = UNSIGNED;
	}
	ntype = ctype(ntype);
	p = xbcon(v, NULL, ntype);
	ASGLVAL(p->n_slval, v);

	return p;
}

/*
 * Convert a character constant to an integer.
 */
NODE *
charcon(void)
{
	int lastcon = 0;
	int val, i = 0;
	char *pp = yytext;

	if (*pp == 'L')
		pp++;
	pp++;
	while (*pp != '\'') {
		if (*pp++ == '\\') {
			val = esccon(&pp);
		} else
			val = pp[-1];
		makecc(val, i);
		i++;
	}

	if (i == 0)
		uerror("empty character constant");
	if (i > (SZINT/SZCHAR) || (i>1))
		werror("too many characters in character constant");
	return bcon(lastcon);
}

NODE *
wcharcon(void)
{
	unsigned int lastcon = 0;
	unsigned int val, i = 0;
	char *pp = yytext;

	if (*pp == 'L')
		pp++;
	pp++;
	while (*pp != '\'') {
		if (*pp++ == '\\') {
			val = esccon(&pp);
		} else
			val = pp[-1];
#if WCHAR_SIZE == 2
		lastcon = (lastcon << 16) | (val & 0xFFFF);
#else
		lastcon = val;
#endif
		i++;
	}

	if (i == 0)
		uerror("empty wide character constant");
	if (i > 1)
		werror("too many characters in wide character constant");
	return xbcon(lastcon, NULL, ctype(UNSIGNED));
}

void
control(int t)
{
	char *wr = yytext;
	char *eptr;
	int val;

	wr++;	/* Skip initial '#' */
	switch (t) {
	case CPP_IDENT:
		return;	/* Just skip these for now. */

	case CPP_LINE:
		wr += 4;
		/* FALLTHROUGH */
	case CPP_HASH:
		val = strtol(wr, &eptr, 10);
		if (wr == eptr)	/* Illegal string */
			goto bad;
		wr = eptr;
		lineno = val - 1;
		while (*wr && *wr != '\"')
			wr++;
		if (*wr == 0)
			return;
		if (*wr++ != '\"')
			goto bad;
		eptr = wr;
		while (*wr && *wr != '\"')
			wr++;
		if (*wr != '\"')
			goto bad;
		*wr = 0;
		ftitle = addstring(eptr);
#ifdef STABS
		if (gflag)
			stabs_file(ftitle);
#endif
	}
	return;
bad:
	werror("%s: illegal control", yytext);
}

/*
 * split a pragma string in parts.
 */
static char **
splitup(char *str)
{
	char *s, **ary;
	int i;

	/* count ws. at least needed array size, add 2 to terminate */
	for (i = 2, s = str; *s; s++)
		if (*s == ' ' || *s == '\t' ||
		    *s == '(' || *s == ')' || *s == ',')
			i++;
	ary = tmpalloc(sizeof(char *)*i);
	for (i = 0, s = strtok(str, " \t(,)"); s; s = strtok(NULL, " \t(,)"))
		ary[i++] = s;
	ary[i] = NULL;
	return ary;
}

int pragma_allpacked;
int pragma_packed, pragma_aligned;
char *pragma_renamed;

/*
 * got a full pragma line.  Split it up here.
 */
static void
pragma()
{
	char **ary;

	ary = splitup(yytext);
	if (ary[1] == NULL)
		goto bad;
	if (strcmp(ary[1], "pack") == 0) {
		pragma_allpacked = ary[2] ? atoi(ary[2]) : 0;
	} else if (strcmp(ary[1], "packed") == 0) {
		pragma_packed = ary[2] ? atoi(ary[2]) : 1;
	} else if (strcmp(ary[1], "aligned") == 0) {
		pragma_aligned = ary[2] ? atoi(ary[2]) : 1;
	} else if (strcmp(ary[1], "rename") == 0) {
		pragma_renamed = newstring(ary[2], strlen(ary[2]));
	} else if (strcmp(ary[1], "GCC") == 0) {
		/* pragma_gcc(); Ignored for now */
	} else if (strcmp(ary[1], "weak") == 0) {
		struct symtab *sp = lookup(addname(ary[2]), SNORMAL);
		sp->sap =
		    attr_add(sp->sap, gcc_attr_parse(bdty(NAME, "weak")));
		if (ary[3])
			uerror("too many arguments to #pragma weak");
	} else if (mypragma(ary)) {
		return;
	} else {
bad:
		if (Wunknown_pragmas)
			werror("unknown pragma");
	}
}

void
cunput(char c)
{
	unput(c);
}

